package hw6.page_objects.enums;

public enum Location {
    HEADER_SECTION,
    CENTER,
    GREEN_PICTURES,
    UNDER_GREEN_PICTURES,
    LEFT_SECTION,
    LOG_SECTION,
    FOOTER,
    FRAME,
    SERVICE_HEADER,
    SERVICE_LEFT,
    DIFFERENT_ELEMENTS,
    CHECKBOXES,
    RADIO_BUTTONS,
    DROPDOWN,
    DROPDOWN_OPTIONS,
    BUTTONS,

    TYPE_DROPDOWNS,
    USER_NAMES,
    DESCRIPTION_IMAGES,
    DESCRIPTION_TEXTS,

    VIP_CHECKBOX
}
